### ISSUE TITLE
Formatting for Julia files in VS Code not picking up the style

### ISSUE THREAD

**Issue by jlperla** [quarto-dev/quarto#101]
I tested #95  and it indeed works! 

However, it seems like the formatting is not correctly picking up the formatting file.  To test this, create a file called
`.JuliaFormatter.toml` with the following text
```toml
style = "sciml"
```

Then create a `qmd` file with a julia cell block that has
```julia
function f(x,
y; a=1)
return a+x
end
```
Or something poorly formatted like that.  Put the same thing in a `.jl` file

If you run the formatter on the .`jl` file then it correctly picks up the formatting file and changes it to
```julia
function f(x,
           y; a = 1)
    return a + x
end
```
which is correctly using the `sciml` style.

If you run it in the qmd file instead, then it does
```julia
function f(x,
    y; a=1)
    return a + x
end
```

Which is using the default settings, which nobody uses :-)

I am not sure exactly how you are calling the formatter, but you might want to doublecheck where the process is running since it will walk up the directory to find style files.

**Comment by jjallaire** [comment]
Thanks for reporting this! The issue was that we were running the formatter in a temporary directory (we need to synthesize a `.jl` file from the `.qmd` file for the formatter to run on). I've changed this to run on a temporary file within the directory where the `.qmd` is located and it does indeed now seem to pick up the configured formatter: https://github.com/quarto-dev/quarto/commit/e818ebb504b5e6302149575ff9cf4878088a09b3

This is available now in our v1.71.0 release.
