### ISSUE TITLE
[Feature Request] Preview docusaurus site in VS Code

### ISSUE THREAD

**Issue by FabienSe** [quarto-dev/quarto#138]
The preview provided by the VS Code extension only support rendering of Quarto documents (both standalone and within websites or books). It does not support preview of generated docusaurus site.

![image](https://user-images.githubusercontent.com/106662952/233017386-950bba6a-d956-4eaf-8d40-8a5e88750a4c.png)

Both preview can be started with quarto `quarto preview` command and are started on localhost with a specific port.

At the moment, a workaround is to use the embedded VS Code command `simpleBrowser.show` and passing the URL of the site.
It can be way more convenient that quarto support this out of box.

Thanks !

**Comment by jjallaire** [comment]
Preview does indeed support Docusaurus sites (however there is one issue described below which may have prevented you from seeing this). 

If you start with a simple docusaurus website and then open it in VS Code:

```bash
npx create-docusaurus@latest docusaurus-website classic
cd docusaurus-website
code .
```

At this point the **Quarto: Render Project** command _should have_ worked to start the preview, however it wasn't b/c we were insisting upon seeing a `_quarto.yml` file to identify a project. This is remedied here and will be in the next release of the extension: https://github.com/quarto-dev/quarto/commit/6e123a119dfe8313d5b735cbbc0d82eee92cc57b

However, if you e.g. rename one of the blog posts to have a `.qmd` extension, the Render command (Cmd+Shift+K) should result in Quarto Preview being invoked for the site even w/o the fix above. Note that the preview always starts at the home page rather than at the document which was rendered (an issue we don't currently know how to circumvent).
