### ISSUE TITLE
No Julia unicode autocomplete in visual editing mode

### ISSUE THREAD

**Issue by bthorne93** [quarto-dev/quarto#177]
When editing Julia code snippets in visual editing mode in VSCode I do not have access to unicode auto complete (e.g. `\beta` does not autocomplete to the actual symbol). I have no such problem in source editing mode.

**Comment by jjallaire** [comment]
Thanks for reporting this! Should be fixed here: https://github.com/quarto-dev/quarto/commit/59a6b5e03bf03bb88054545175c4c5338dcc578a

**Comment by bthorne93** [comment]
Thank you for addressing this, now it works when autocompleting on isolated lines. However, no prompt appears when working in the middle of a line, e.g.

```julia
ϕ = 0:0.1:2π
sin(2\phi)
```

**Comment by jjallaire** [comment]
This is tricky for us to get right -- we are trying to identify the "token" to complete against (while being permissive about what is included in tokens). Here the "token" includes the 2 because there is no space after the 2 and as a result no completions are yielded. We have don't the full global awareness of the language so are using heuristics which aren't quite getting it right. It's not a great workaround but if you insert a space before entering `\phi` you'll see the completions.
