### ISSUE TITLE
v1.86.2 very very slow

### ISSUE THREAD

**Issue by DamonCharlesRoberts** [quarto-dev/quarto#188]
I love this plugin! Lately, though, things have gotten pretty slow. Is there some way to speed this up? Scale back some of the features?

Some examples:
- Looking at Startup activation, it takes 3861ms this is relative to my next slowest plugin which is Python at 74ms.
- When opening VSCode on Windows, I get a message asking me if I want to close, restart, or wait for the window (likely due to activation time being at almost 4 seconds for this plugin alone).
- Recognition of code blocks takes quite a while to happen.
- Waited for about 10 minutes for an R plot to open. Made sure it wasn't my R plugin by uninstalling the Quarto plugin and I had no issues.

**Comment by jjallaire** [comment]
Hi Damon, thanks for reporting this! We did make a major architectural change in v1.86 which was to start using Pandoc to parse markdown (rather than markdown-it, which was okay but had lots of edge cases which made for janky tokenization of blocks).

Anyway, my guess is that running pandoc on windows has more startup overhead (and slower overall performance) than on OS X and that is the source of the problem. I think we could bring back the markdown-it parser just for Windows and make it an option for other platforms as well (we could even auto-detect if parsing is taking too long and fault back to markdown-it).

One thing it would be very helpful to know is whether you are running in a workspace that has a large number of markdown documents? (as it does attempt to index all of them at startup). If this is the case we could try throttling that indexing as well.

**Comment by DamonCharlesRoberts** [comment]
Makes sense!! 

Thanks for such a fast response! I've only got 3 markdown docs in the directory. So not too many.

**Comment by jjallaire** [comment]
One other possibility to consider is that we've Windows Defender interfere w/ running Pandoc in the past (it doesn't prevent it entirely, but just slows it down w/ tons of extra checks). While you are in the longer startup sequence do you see Windows Defender (or any other anti-malware tools) taking a bunch of CPU time?

**Comment by DamonCharlesRoberts** [comment]
Interesting. But no, I don't see that happening.

**Comment by jgsw** [comment]
I've experienced slowness as well on Windows since 1.86. For me it's not just slowness in startup, but also when you're typing into a document. I think the suggestion about Microsoft Defender is correct - I can see it spiking in CPU when there is slowness in updating a Quarto document.

**Comment by jjallaire** [comment]
Thanks, I think Windows Defender is a likely culprit. It sees Pandoc running from an unknown context (e.g an extension) and subjects it to extra scrutiny. We will revert to using markdown-it on Windows (should have that release out in a day or two)

**Comment by bairdj** [comment]
I have also experienced this on Windows, with extremely slow performance on this version. It is when typing in documents that I really notice the slowness. I also tried this on a fresh project with one qmd file and it was still slow. I profiled the extension (attached), which seems to me to show that the `parsePandocDocument` call is the culprit (97.35% self time).

[CPU-20230531T152538.236Z.cpuprofile.txt](https://github.com/quarto-dev/quarto/files/11616058/CPU-20230531T152538.236Z.cpuprofile.txt)

**Comment by sakai-nako** [comment]
Even in the Japanese environment of M1 Mac, Japanese conversion is considerably slower when using 1.86.0.
I have temporarily reverted to 1.85.0 and am using it.

It may be a compatibility between pandoc and Japanese conversion, but I'm writing this just in case it may be of some help!

**Comment by jjallaire** [comment]
Thanks @bairdj for the additional diagnostics. We just shipped v1.87.0 which reverts to using markdown-it for parsing, which should remedy all of the issues reported in this thread. Thanks everyone for your patience on this issue!
