### ISSUE TITLE
Quarto: Render in VSCode extension no longer shows preview as of v1.100.0

### ISSUE THREAD

**Issue by phinate** [quarto-dev/quarto#288]
On my machine (Mac M2 Pro), I can reproduce the behaviour of running `Quarto: Render` and having no preview shown, from v1.100.0 and later. v1.99.0 and lower does not have this issue.

In particular, the command run switches from 
```
quarto preview my_project --render all --no-browser --no-watch-inputs   # v1.99.0
```

to just 

```
quarto render   # v1.100.0
```

which does not handle the integrated preview anymore.

**Comment by jjallaire** [comment]
Starting with v1.100.0 there are now two different modes (to match the similarly named modes in the CLI)

1) **Quarto: Preview** -- renders a single format and shows a preview (this is identical to the previous Quarto: Render)

2) **Quarto: Render** -- render all formats and do not show a preview.

So TLDR just use **Quarto: Preview** instead (the keyboard shortcuts that used to be bound to render is now bound to preview, and there is a render button rather than preview button on the editor toolbar).
