### ISSUE TITLE
Quarto Help does not fix for a function for R, but changes for every parameter. 

### ISSUE THREAD

**Issue by Fred-Wu** [quarto-dev/quarto#30]
It would be helpful if the contextual help could be fixed for a function. At the moment, when the cursor is moved into parentheses, it then turns to provide a summary information for that function. 

<img width="525" alt="image" src="https://user-images.githubusercontent.com/4111978/182502705-db3fb419-ef53-467c-89b8-0c72c0321a17.png">

Also, when I type such as `data` in the function, it then changes to the following, which is the information for the first highlight of autocomplete

<img width="525" alt="image" src="https://user-images.githubusercontent.com/4111978/182503128-4a534f83-5f92-4b58-b1ec-3048db978028.png">

<img width="344" alt="image" src="https://user-images.githubusercontent.com/4111978/182503665-ec9ea7c9-4a5e-4ecf-8a8d-f9504d32b703.png">

Also, only after after typing `data=`, and remove `=`,  will it show parameter help. 

`data=`

<img width="524" alt="image" src="https://user-images.githubusercontent.com/4111978/182504002-527477f3-c632-4ab2-bdfc-0d5e8d180851.png">

remove`=`
<img width="524" alt="image" src="https://user-images.githubusercontent.com/4111978/182504049-499f8f71-16a1-4428-88cc-b0e0e1769a0e.png">

**Comment by jjallaire** [comment]
We are currently just calling the `hover` API to get this help (so whatever the VS Code R extension shows on hover we show in contextual help). If you want to see this refined I'd suggest providing feedback on the R extension then we'll pickup these changes automatically.

Note that there is also a "pin" capability on Quarto Help which will freeze the current contents of the view (which would allow you to e.g. maintain the full function documentation rather than moving on to parameter docs)
