### ISSUE TITLE
Bug: Quarto VSCode extenstion not refreshing markdown

### ISSUE THREAD

**Issue by gsingh91** [quarto-dev/quarto#403]
I am using the Quarto VSCode extension version `1.111.0` and quarto version `1.4.551`. When use the quarto render feature, it renders successfully but any changes made during the rendering are not picked up in the output. I captured the behaviour: 

![screengrab](https://github.com/quarto-dev/quarto/assets/12013337/6cace930-4d1b-421f-ab00-b76dcd222f01)

it was working till early last week, but has not been working now. Not sure what has changed. I have also checked with another colleague and they are seeing the same issue. Let me know if more information is needed.

**Comment by kmasiello** [comment]
I have done testing in various environments and have the same issue with 
Quarto v 1.5.27, extension v 1.111.0
Quarto v 1.3.340, extension v 1.79.0

**Comment by cderv** [comment]
I do think current status is to not re-render by default unless Render On Save configuration is set. 

See this related issue and comments : 
* https://github.com/quarto-dev/quarto/issues/307#issuecomment-1774196673

See about Render on Save at https://quarto.org/docs/tools/vscode.html#render-on-save
> By default Quarto does not automatically render .qmd or .ipynb files when you save them. This is because rendering might be very time consuming (e.g. it could include long running computations) and it’s good to have the option to save periodically without doing a full render.

So I don't think you have a new updated preview unless you re-render or this configuration is active. 

> it was working till early last week, but has not been working now. Not sure what has changed.

Did you update the extension recently?  Or maybe add this option set and now unset ? 

I looked if this would have changed since #307

**Comment by gsingh91** [comment]
Thanks @cderv . I could not figure out if the setting changed recently, but changing it back worked for me. We can close this issue, appreciate your help.
