### ISSUE TITLE
Quarto should support  JupyterLab syntax for Mermaid charts

### ISSUE THREAD

**Issue by stefansimik** [quarto-dev/quarto#445]
Problem is, that this code works in JupyterLab flawlessly and immediately renders chart:
~~~ 
```mermaid
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
```
~~~ 

```mermaid
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
```

but to make it usable with Quarto rendering, we have to wrap "mermaid" into curly brackets ,
which completely breaks functionality in JupyterLab and it works only during Quarto rendering.

~~~ 
```{mermaid}
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
```
~~~ 

## Expected fix
1. We should keep basic compatibility with Jupyter - so we can write **classic supported Mermaid charts in JupyterLab ** (= without curly brackets) and still be rendered nicely using Quarto rendering.
2. The same problem will probably apply to Graphviz charts.

**Comment by cscheid** [comment]
Thanks for the suggestion, but we're not going to do that. We already have notation for it.

**Comment by cderv** [comment]
> flawlessly and immediately renders chart

@stefansimik just curious: is this the missing piece  ? 

Are you using the Quarto Extension for Jupyter Lab already ? https://quarto.org/docs/tools/jupyter-lab.html

I am mentioning this because, with this extension, the mermaid cells will also be rendered live in Jupyter Lab when using the Quarto syntax. 
![chrome_4F61Aiqesb](https://github.com/quarto-dev/quarto/assets/6791940/8d00e906-f875-48dd-af09-e72ed87d81f8)
This document can then be previewed and rendered using Quarto to any of the supported output formats. 

Maybe this helps.

**Comment by stefansimik** [comment]
Thank you @cderv 
I haven't tried yet JupyterLab extension for Quarto, but going to do so immediately.
Looks like an elegant solution, that I was looking for 👍

**Comment by cderv** [comment]
> I tested it and it works flawlessly. Love you for letting me know ❤️

Awesome !
