### ISSUE TITLE
Detect Pixi installation of Quarto in the VS Code Extension

### ISSUE THREAD

**Issue by roaldarbol** [quarto-dev/quarto#573]
I'm installing Quarto with [pixi](https://pixi.sh), which means the executable is located within the project, and lives at:
```
.pixi/envs/default/bin/quarto
```
It would be great to have the VS Code extension automatically detect this installation, like it does `venv` and others, if a `.pixi` folder is present.

**Comment by cscheid** [comment]
I don't think we should be getting in the business of supporting every package manager out there. `venv` is effectively the Python standard and gets special treatment by VS Code, and that's why we support it. I'm sorry, but I'm going to go ahead and close this one; we don't have the resources to do this well enough, and I don't think we will in the near future.

**Comment by roaldarbol** [comment]
I think that's an unfortunate choice, especially with the extension being a cornerstone in Positron.
I personally know very few people who actually use the base `venv`, whereas especially `conda`-based tools are widely used, and `uv` is also getting a lot of traction. Now, uv saves into `.venv` by default, so I imagine *that* is already autodetected. All other `conda` venv's install into global caches (and so does Poetry); `pixi` is the only one that does so within the project. Python installations from pixi is already being [discovered by the vs-code-python extension](https://github.com/microsoft/vscode-python/pull/22968), and [is also discovered in Positron](https://github.com/posit-dev/positron/issues/3724#issuecomment-2420240152). 

As far as I can tell from [the source code](https://github.com/quarto-dev/quarto/blob/main/apps/vscode/src/core/quarto.ts), you already support `conda` too, which is great as it's widely used. If I read the source correctly (which I may not be), you're basically just checking whether there exists a Quarto installation in the same place as the Python Interpreter is located; so essentially it's mostly relaxing some constraints in `python.ts` on where that is allowed to be.

It's of courser completely up to you, but I think it would be worth discussing with the Positron team too before completely dismissing the idea.

**Comment by cscheid** [comment]
To clarify:

- Positron inherits its pixi handling from their fork of Microsoft's Python extension, as you can verify by the following code search: https://github.com/search?q=repo%3Aposit-dev%2Fpositron+pixi&type=code
- Pixi, as of 2023, is used by _at most_ 4% of the respondents of the [Python Developers Survey](https://lp.jetbrains.com/python-developers-survey-2023/), since it's not named there:
  ![Image](https://github.com/user-attachments/assets/54098d3e-9c47-4677-b87c-a579a4d56cf9)

  In contrast, Conda accounts for 20% of the usage.

My decision is not out of a desire to _not_ support Pixi. It's a decision based on the other things we have to support. We're happy to revisit that decision in light of more data, and if you're willing to contribute a PR, we would likely even take it. But as a feature request for _us_ to do, I stand by my original point: I don't see it coming to the top of our priority list, and I don't think letting this issue linger open will help anyone.

**Comment by roaldarbol** [comment]
Makes complete sense, I can definitely see your points. I'm actually surprised by the numbers, but they speak for themselves.
