### ISSUE TITLE
Positron's help panel is not used when F1 is invoked

### ISSUE THREAD

**Issue by andrewheiss** [quarto-dev/quarto#580]
Currently, in VS Code, pressing F1 inside a function name opens the documentation in a special "Quarto: Help" panel in the File Explorer:

![Image](https://github.com/user-attachments/assets/dff8eba0-9c60-490f-b3a3-3543f3c5da72)

That's great when using VS Code because it doesn't have a dedicated help panel like RStudio does.

However, in the spirit of RStudio, Positron *does* have a dedicated help panel—when pressing F1 in a regular R script in Positron, the documentation opens there:

![Image](https://github.com/user-attachments/assets/a05c5a65-cd02-4b5d-8608-65a0e8208162)

When pressing F1 in a Quarto file in Positron, though, nothing happens in the Positron help panel. Instead, the documentation appears in the custom Quarto help panel:

![Image](https://github.com/user-attachments/assets/457d3ddf-dcda-4014-836c-b7421f61d2ff)

There's an issue at Positron tracking this: https://github.com/posit-dev/positron/issues/4097 and it's part of a larger push for better Quarto improvements (https://github.com/posit-dev/positron/issues/4858). I figured that F1 wasn't doing anything at all (I'd forgotten about Quarto's custom help panel), and others likely thought the same, but a recent comment https://github.com/posit-dev/positron/issues/4097#issuecomment-2427178059 discovered that F1 is actually working as expected in Positron—it's just invisible if the custom Quarto help panel is hidden.

So the underlying issue seems to be that Quarto's VS Code extension is hijacking F1 inside Positron

**Comment by juliasilge** [comment]
It turns out this is the `quarto-assist` webview the Quarto extension contributes; it can be pinned/unpinned with commands `quarto.assist.pin` and `quarto.assist.unpin`. There are three kinds of things that can get rendered in this webview:

https://github.com/quarto-dev/quarto/blob/227af7814a1e42737383ed4ce361242c36504dad/apps/vscode/src/providers/assist/render-assist.ts#L43-L45

Once you get this webview going, it responds to where your cursor is and renders things for you, depending on whether it is an equation, a function etc. The Help does not seem to work for Python for me, and I have not found a pydoc server or anything like that.

One option would be to turn this webview off in Positron and hook up <kbd>F1</kbd> to calling Positron's Help; it does seem like most use of it is for Help from the issues about it. Or I guess we can pipe through <kbd>F1</kbd> to Positron's Help without messing with this at all, and they both would be available.

Real talk: I had never pulled up this webview until starting to look into this today.

**Comment by juliasilge** [comment]
The command in Positron is `positron.help.showHelpAtCursor` here:
https://github.com/posit-dev/positron/blob/465058d309f13331ba2f458f8e99e6d5eeaea541/src/vs/workbench/contrib/positronHelp/browser/positronHelpActions.ts#L32

The command goes to a help topic provider that is a `languageFeaturesService` which I guess is different from a `languageFeaturesRegistry` (what the statement range provider is); still we'll probably need something along the lines of https://github.com/posit-dev/positron/pull/3107/ in Positron to pipe it through.

**Comment by juliasilge** [comment]
I got this wrapped up in #599 plus https://github.com/posit-dev/positron/issues/4097. I'm going to close this now but just FYI @andrewheiss the fix in Positron hasn't been promoted to a public build yet and probably won't be until early next week. When that happens, you'll need a) the new Positron build and b) the dev Quarto extension version. You can get a development version of the Quarto extension by downloading [the artifact built here](https://github.com/quarto-dev/quarto/actions/runs/11751844180), unzipping it, install the `.vsix` from the command palette (i.e. manually install the extension from a local file), and then restarting Positron.

Thanks again for the report! 🙌

**Comment by andrewheiss** [comment]
woohoo! Thanks for the quick fix!
